{
 "title": "Ecowitt Weather Station",
 "description": "Ecowitt exporter",
 "tags": [
  "weather",
  "ecowitt"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temp_c{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(humidity_percent{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "baromrel_hpa{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windspeed_mph{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mm/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rainrate_mm{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunlight",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarradiation_wm2{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Indoor",
     "expr": "label_replace(label_replace(temp_c{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "http_listener_v2",
     "query": "SELECT (mean(\"tempinf\")-32) * 5/9 FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tempinf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outdoor",
     "expr": "label_replace(label_replace(tempin_c{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "http_listener_v2",
     "query": "SELECT (mean(\"temp1f\")-32)*5/9 FROM \"http_listener_v2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp1f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "Barometric Pressure",
     "expr": "label_replace(label_replace(baromrel_hpa{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "http_listener_v2",
     "select": [
      [
       { "params": [ "baromrelin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "baromabs_hpa", "legendFormat": "__auto" }
   ]
  },
  { "title": "Rainfall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Hourly rainfall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "Rain",
     "expr": "label_replace(label_replace(hourlyrain_mm{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily rainfall",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(dailyrain_mm{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(windspeed_mph{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(label_replace(label_replace(windgust_mph{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(winddir_degree{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "UV index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(uv{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar irradiation",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 39 },
   "targets": [
    {
     "expr": "label_replace(label_replace(solarradiation_wm2{container=\"ecowitt-exporter\"}, \"pod\", \"\", \"pod\", \"(.*)\"), \"instance\", \"\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}