{
 "title": "Solar power data",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cloud power usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nut_load*700", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Solar power generation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aurora_grid_power_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proportion of cloud power usage covered by solar",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum(aurora_grid_power_reading{} or vector(0.1)) / sum(nut_load{}*700), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time on solar over last 24h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(clamp_max(sum(aurora_grid_power_reading{} or vector(1)) / sum(nut_load{}*700), 1)[24h:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Solar power generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "aurora_grid_power_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cloud power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time((nut_load{}*670)[3m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar radiation reaching Earth",
   "type": "timeseries",
   "description": "Solar insolation as measured by the weather station",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    { "expr": "solarradiation_wm2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proportion of cloud power usage covered by solar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(sum(aurora_grid_power_reading{} or vector(1)) / sum(nut_load{}*700), 1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}