{
 "title": "Temperatures",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\", sensor=\"temp0\", service!=\"rpi-metrics\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "NVMe temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"nvme_nvme0\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ambient temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecowitt_temp_c{container=\"ecowitt-exporter\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}